package com.riguz.jfork.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSecurityGroupPermission<M extends BaseSecurityGroupPermission<M>> extends Model<M> implements IBean {

	public void setGroupId(java.lang.String groupId) {
		set("group_id", groupId);
	}

	public java.lang.String getGroupId() {
		return get("group_id");
	}

	public void setPermissionId(java.lang.String permissionId) {
		set("permission_id", permissionId);
	}

	public java.lang.String getPermissionId() {
		return get("permission_id");
	}

}
