package com.riguz.jfork.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuthPassword<M extends BaseAuthPassword<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setFromDate(java.util.Date fromDate) {
		set("from_date", fromDate);
	}

	public java.util.Date getFromDate() {
		return get("from_date");
	}

	public void setThruDate(java.util.Date thruDate) {
		set("thru_date", thruDate);
	}

	public java.util.Date getThruDate() {
		return get("thru_date");
	}

}
