package com.riguz.jfork.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		// Composite Primary Key order: from_date,user_id
		arp.addMapping("auth_password", "from_date,user_id", AuthPassword.class);
		arp.addMapping("security_group", "group_id", SecurityGroup.class);
		// Composite Primary Key order: group_id,permission_id
		arp.addMapping("security_group_permission", "group_id,permission_id", SecurityGroupPermission.class);
		arp.addMapping("security_permission", "permission_id", SecurityPermission.class);
		// Composite Primary Key order: from_date,group_id,user_id
		arp.addMapping("user_login_security_group", "from_date,group_id,user_id", UserLoginSecurityGroup.class);
		arp.addMapping("user_profile", "user_id", UserProfile.class);
	}
}

