package com.riguz.jfork.model;

import com.riguz.jfork.model.base.BaseAuthPassword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthPassword extends BaseAuthPassword<AuthPassword> {
	public static final AuthPassword dao = new AuthPassword();
}
