package com.riguz.jfork.model;

import com.riguz.jfork.model.base.BaseSecurityGroupPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecurityGroupPermission extends BaseSecurityGroupPermission<SecurityGroupPermission> {
	public static final SecurityGroupPermission dao = new SecurityGroupPermission();
}
