package com.riguz.jfork.model;

import com.riguz.jfork.model.base.BaseSecurityPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecurityPermission extends BaseSecurityPermission<SecurityPermission> {
	public static final SecurityPermission dao = new SecurityPermission();
}
