package com.riguz.jfork.model;

import com.riguz.jfork.model.base.BaseSecurityGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecurityGroup extends BaseSecurityGroup<SecurityGroup> {
	public static final SecurityGroup dao = new SecurityGroup();
}
