package com.riguz.jfork.model;

import com.riguz.jfork.model.base.BaseUserProfile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserProfile extends BaseUserProfile<UserProfile> {
	public static final UserProfile dao = new UserProfile();
}
