package com.riguz.jfork.model;

import com.riguz.jfork.model.base.BaseUserLoginSecurityGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLoginSecurityGroup extends BaseUserLoginSecurityGroup<UserLoginSecurityGroup> {
	public static final UserLoginSecurityGroup dao = new UserLoginSecurityGroup();
}
